// Setup script to fix Prisma client module resolution
const fs = require('fs');
const path = require('path');

const prismaClientPath = path.join(__dirname, '../node_modules/.prisma/client');
const defaultDir = path.join(prismaClientPath, 'default');

// Create default directory if it doesn't exist
if (!fs.existsSync(defaultDir)) {
  fs.mkdirSync(defaultDir, { recursive: true });
}

// Create index.js that exports PrismaClient properly
// This file will be processed by webpack, which will handle the TypeScript client
const indexContent = `// Auto-generated by setup-prisma.js
// Export PrismaClient for @prisma/client/default.js
'use strict';

// This module will be processed by webpack
// Webpack will resolve the '../client' import and bundle the TypeScript client
// For now, we export a placeholder that webpack will replace
module.exports = require('../client');
`;

fs.writeFileSync(path.join(defaultDir, 'index.js'), indexContent);
console.log('✅ Prisma client default directory setup complete');
